# Generated by Django 4.2.11 on 2024-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_machine_id_alter_productionlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='actual_output',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='good_products',
            field=models.IntegerField(default=0),
        ),
    ]
